export const PERMISSIONS = {
    MENU_DASHBOARD: 'MENU:DASHBOARD',
    MENU_USER_MANAGEMENT: 'MENU:USER_MANAGEMENT',
    MENU_CATALOG: 'MENU:CATALOG',
    MENU_INVENTORY_CORE: 'MENU:INVENTORY_CORE',
    MENU_ADVANCED_INVENTORY: 'MENU:ADVANCED_INVENTORY',
    MENU_PROCUREMENT: 'MENU:PROCUREMENT',
    MENU_SALES: 'MENU:SALES',
    MENU_ACCOUNTING: 'MENU:ACCOUNTING',
    MENU_PLUGINS: 'MENU:PLUGINS',
    MENU_ANALYTICS: 'MENU:ANALYTICS',
    MENU_SETTINGS: 'MENU:SETTINGS',
};

export const PERMISSION_LABELS = {
    [PERMISSIONS.MENU_DASHBOARD]: 'Dashboard Access',
    [PERMISSIONS.MENU_USER_MANAGEMENT]: 'User & Role Management',
    [PERMISSIONS.MENU_CATALOG]: 'Product Catalog',
    [PERMISSIONS.MENU_INVENTORY_CORE]: 'Core Inventory Operations',
    [PERMISSIONS.MENU_ADVANCED_INVENTORY]: 'Advanced Inventory Features',
    [PERMISSIONS.MENU_PROCUREMENT]: 'Procurement & Suppliers',
    [PERMISSIONS.MENU_SALES]: 'Sales & POS',
    [PERMISSIONS.MENU_ACCOUNTING]: 'Accounting & Finance',
    [PERMISSIONS.MENU_PLUGINS]: 'Plugins & Integrations',
    [PERMISSIONS.MENU_ANALYTICS]: 'Analytics & Reports',
    [PERMISSIONS.MENU_SETTINGS]: 'System Settings',
};
