const LANGUAGE_OPTIONS = [
    { value: 'en', label: 'English' },
    { value: 'bn', label: 'Bangla' },
];

const TIMEZONE_OPTIONS = [
    { value: 'Asia/Dhaka', label: 'Asia/Dhaka (GMT+6)' },
    { value: 'Asia/Kolkata', label: 'Asia/Kolkata (GMT+5:30)' },
    { value: 'UTC', label: 'UTC' },
];

const CURRENCY_OPTIONS = [
    { value: 'BDT', label: 'BDT' },
    { value: 'USD', label: 'USD' },
    { value: 'EUR', label: 'EUR' },
];

const YES_NO_OPTIONS = [
    { value: 'true', label: 'Enabled' },
    { value: 'false', label: 'Disabled' },
];

export const SETTINGS_SECTIONS = [
    {
        id: 'general',
        title: 'General',
        description: 'Organization identity, localization, and branding defaults used across the workspace.',
        icon: 'tune',
        accent: 'from-sky-500/12 via-transparent to-cyan-500/12',
        groups: [
            {
                id: 'localization',
                title: 'Localization',
                description: 'Default language, timezone, and currency settings for the tenant.',
                settings: [
                    {
                        key: 'general.localization.defaultLanguage',
                        label: 'Default language',
                        helpText: 'Used as the tenant default for new users and shared UI defaults.',
                        type: 'LANGUAGE',
                        category: 'general',
                        control: 'select',
                        options: LANGUAGE_OPTIONS,
                        defaultValue: 'en',
                    },
                    {
                        key: 'general.localization.defaultTimezone',
                        label: 'Default timezone',
                        helpText: 'Used for timestamps on reports, receipts, and operational logs.',
                        type: 'TIMEZONE',
                        category: 'general',
                        control: 'select',
                        options: TIMEZONE_OPTIONS,
                        defaultValue: 'Asia/Dhaka',
                    },
                    {
                        key: 'general.localization.defaultCurrency',
                        label: 'Default currency',
                        helpText: 'Primary currency used for valuation, POS, and operational totals.',
                        type: 'CURRENCY',
                        category: 'general',
                        control: 'select',
                        options: CURRENCY_OPTIONS,
                        defaultValue: 'BDT',
                    },
                ],
            },
            {
                id: 'branding',
                title: 'Branding',
                description: 'Organization identity displayed on printed or shared artifacts.',
                settings: [
                    {
                        key: 'general.organization.name',
                        label: 'Organization name',
                        helpText: 'Appears on documents, receipts, and tenant-facing UI.',
                        type: 'STRING',
                        category: 'general',
                        control: 'input',
                        defaultValue: 'Master Inventory',
                        placeholder: 'Organization name',
                    },
                    {
                        key: 'general.branding.receiptFooterText',
                        label: 'Receipt footer text',
                        helpText: 'Shown at the bottom of POS and invoice printouts.',
                        type: 'STRING',
                        category: 'general',
                        control: 'textarea',
                        defaultValue: 'Thank you for your business.',
                        placeholder: 'Footer text for printed receipts',
                    },
                ],
            },
        ],
    },
    {
        id: 'security',
        title: 'Security and Access',
        description: 'Session, password, invitation, and audit behavior for the organization.',
        icon: 'shield',
        accent: 'from-slate-500/15 via-transparent to-slate-400/10',
        groups: [
            {
                id: 'session',
                title: 'Session Policy',
                description: 'Controls how long sessions remain active and when refresh is allowed.',
                settings: [
                    {
                        key: 'auth.session.timeoutMinutes',
                        label: 'Session timeout (minutes)',
                        helpText: 'Users are required to sign in again after this inactivity period.',
                        type: 'NUMBER',
                        category: 'auth',
                        control: 'input',
                        defaultValue: 60,
                        min: 15,
                        step: 5,
                    },
                    {
                        key: 'auth.session.refreshGraceMinutes',
                        label: 'Refresh grace period (minutes)',
                        helpText: 'Controls how long refresh tokens are accepted near session expiry.',
                        type: 'NUMBER',
                        category: 'auth',
                        control: 'input',
                        defaultValue: 15,
                        min: 0,
                        step: 5,
                    },
                ],
            },
            {
                id: 'passwords',
                title: 'Password and Audit Policy',
                description: 'Controls baseline password strength and audit logging.',
                settings: [
                    {
                        key: 'auth.password.minLength',
                        label: 'Minimum password length',
                        helpText: 'Minimum number of characters required for user passwords.',
                        type: 'NUMBER',
                        category: 'auth',
                        control: 'input',
                        defaultValue: 8,
                        min: 8,
                        step: 1,
                    },
                    {
                        key: 'auth.auditLog.userActionsEnabled',
                        label: 'Audit user actions',
                        helpText: 'Record important account and access events for review.',
                        type: 'BOOLEAN',
                        category: 'auth',
                        control: 'boolean',
                        defaultValue: true,
                        risk: 'standard',
                    },
                ],
            },
        ],
    },
    {
        id: 'catalog',
        title: 'Catalog and Product Rules',
        description: 'Standards for SKU generation, attributes, and product creation behavior.',
        icon: 'category',
        accent: 'from-violet-500/12 via-transparent to-fuchsia-500/12',
        groups: [
            {
                id: 'sku',
                title: 'SKU Rules',
                description: 'Default behavior for generated identifiers and product setup.',
                settings: [
                    {
                        key: 'catalog.sku.autoGenerate',
                        label: 'Auto-generate SKU values',
                        helpText: 'Generate SKU values when product creators leave the field empty.',
                        type: 'BOOLEAN',
                        category: 'catalog',
                        control: 'boolean',
                        defaultValue: true,
                    },
                    {
                        key: 'catalog.sku.template',
                        label: 'SKU template',
                        helpText: 'Template used when SKU auto-generation is enabled.',
                        type: 'STRING',
                        category: 'catalog',
                        control: 'input',
                        defaultValue: 'SKU-{CATEGORY}-{SEQ}',
                        placeholder: 'Example: SKU-{CATEGORY}-{SEQ}',
                    },
                ],
            },
            {
                id: 'productDefaults',
                title: 'Product Defaults',
                description: 'Validation rules that apply during product and attribute creation.',
                settings: [
                    {
                        key: 'catalog.product.requireCategory',
                        label: 'Require category for products',
                        helpText: 'Prevent saving a product without assigning it to a category.',
                        type: 'BOOLEAN',
                        category: 'catalog',
                        control: 'boolean',
                        defaultValue: true,
                    },
                    {
                        key: 'catalog.attributes.maxOptionsPerAttribute',
                        label: 'Maximum options per attribute',
                        helpText: 'Limits option count for dropdown or multi-select attribute types.',
                        type: 'NUMBER',
                        category: 'catalog',
                        control: 'input',
                        defaultValue: 20,
                        min: 1,
                        step: 1,
                    },
                ],
            },
        ],
    },
    {
        id: 'inventory',
        title: 'Inventory Rules',
        description: 'Controls core stock behavior across movements, thresholds, and warehouse defaults.',
        icon: 'inventory_2',
        accent: 'from-blue-500/15 via-transparent to-emerald-500/10',
        groups: [
            {
                id: 'stockPolicy',
                title: 'Stock Policy',
                description: 'Rules that determine how stock can be adjusted and monitored.',
                settings: [
                    {
                        key: 'inventory.stock.allowNegativeStock',
                        label: 'Allow negative stock',
                        helpText: 'Permit transactions that temporarily reduce stock below zero.',
                        type: 'BOOLEAN',
                        category: 'inventory',
                        control: 'boolean',
                        defaultValue: false,
                        risk: 'critical',
                    },
                    {
                        key: 'inventory.stock.defaultLowStockThreshold',
                        label: 'Default low-stock threshold',
                        helpText: 'Fallback threshold used for items without item-level thresholds.',
                        type: 'NUMBER',
                        category: 'inventory',
                        control: 'input',
                        defaultValue: 10,
                        min: 0,
                        step: 1,
                    },
                ],
            },
            {
                id: 'movementPolicy',
                title: 'Movement Controls',
                description: 'Validation for stock adjustments and transfer workflows.',
                settings: [
                    {
                        key: 'inventory.movements.requireReason',
                        label: 'Require movement reason',
                        helpText: 'Require a reason or reference when stock is adjusted.',
                        type: 'BOOLEAN',
                        category: 'inventory',
                        control: 'boolean',
                        defaultValue: true,
                    },
                    {
                        key: 'inventory.transfer.requireApproval',
                        label: 'Require transfer approval',
                        helpText: 'Hold transfer workflows until an approval step is completed.',
                        type: 'BOOLEAN',
                        category: 'inventory',
                        control: 'boolean',
                        defaultValue: false,
                    },
                ],
            },
        ],
    },
    {
        id: 'advancedInventory',
        title: 'Advanced Inventory Controls',
        description: 'Configuration for batches, serials, reservations, replenishment, and valuation.',
        icon: 'domain_verification',
        accent: 'from-emerald-500/15 via-transparent to-lime-500/10',
        groups: [
            {
                id: 'traceability',
                title: 'Batch and Serial Rules',
                description: 'Controls product traceability and required metadata.',
                settings: [
                    {
                        key: 'advancedInventory.batch.requireExpiryDate',
                        label: 'Require batch expiry date',
                        helpText: 'Require expiry dates when working with batch-controlled stock.',
                        type: 'BOOLEAN',
                        category: 'advancedInventory',
                        control: 'boolean',
                        defaultValue: true,
                    },
                    {
                        key: 'advancedInventory.serial.enabled',
                        label: 'Enable serial tracking by default',
                        helpText: 'Use serial tracking as the standard rule for serial-managed items.',
                        type: 'BOOLEAN',
                        category: 'advancedInventory',
                        control: 'boolean',
                        defaultValue: true,
                    },
                ],
            },
            {
                id: 'planning',
                title: 'Planning and Valuation',
                description: 'Defaults for replenishment logic and valuation reporting.',
                settings: [
                    {
                        key: 'advancedInventory.replenishment.defaultCoverageDays',
                        label: 'Replenishment coverage days',
                        helpText: 'Target coverage period used when generating replenishment suggestions.',
                        type: 'NUMBER',
                        category: 'advancedInventory',
                        control: 'input',
                        defaultValue: 14,
                        min: 1,
                        step: 1,
                    },
                    {
                        key: 'advancedInventory.valuation.method',
                        label: 'Valuation method',
                        helpText: 'Default method used by valuation reports and costing workflows.',
                        type: 'ENUM',
                        category: 'advancedInventory',
                        control: 'select',
                        options: [
                            { value: 'FIFO', label: 'FIFO' },
                            { value: 'WEIGHTED_AVERAGE', label: 'Weighted Average' },
                            { value: 'STANDARD_COST', label: 'Standard Cost' },
                        ],
                        defaultValue: 'FIFO',
                    },
                ],
            },
        ],
    },
    {
        id: 'procurement',
        title: 'Procurement Controls',
        description: 'Supplier defaults, purchasing thresholds, and receiving tolerances.',
        icon: 'local_shipping',
        accent: 'from-amber-500/15 via-transparent to-orange-500/10',
        groups: [
            {
                id: 'purchaseOrders',
                title: 'Purchase Order Defaults',
                description: 'Default purchasing settings used when creating requisitions and orders.',
                settings: [
                    {
                        key: 'procurement.purchaseOrder.numberPrefix',
                        label: 'Purchase order number prefix',
                        helpText: 'Prefix applied when generating PO numbers.',
                        type: 'STRING',
                        category: 'procurement',
                        control: 'input',
                        defaultValue: 'PO',
                        placeholder: 'PO',
                    },
                    {
                        key: 'procurement.purchaseOrder.defaultPaymentTermDays',
                        label: 'Default payment term (days)',
                        helpText: 'Used as the standard vendor payment term on purchase orders.',
                        type: 'NUMBER',
                        category: 'procurement',
                        control: 'input',
                        defaultValue: 30,
                        min: 0,
                        step: 5,
                    },
                ],
            },
            {
                id: 'receiving',
                title: 'Receiving Rules',
                description: 'Validation rules for goods receipts and supplier deliveries.',
                settings: [
                    {
                        key: 'procurement.receiving.overReceiptTolerancePercent',
                        label: 'Over-receipt tolerance (%)',
                        helpText: 'Permitted variance above ordered quantity during receiving.',
                        type: 'NUMBER',
                        category: 'procurement',
                        control: 'input',
                        defaultValue: 5,
                        min: 0,
                        step: 1,
                    },
                    {
                        key: 'procurement.receiving.requireReferenceDocument',
                        label: 'Require reference document',
                        helpText: 'Require linked PO or reference information before confirming a receipt.',
                        type: 'BOOLEAN',
                        category: 'procurement',
                        control: 'boolean',
                        defaultValue: true,
                    },
                ],
            },
        ],
    },
    {
        id: 'sales',
        title: 'Sales and Fulfillment Controls',
        description: 'Customer, order, and fulfillment defaults for outbound operations.',
        icon: 'shopping_cart',
        accent: 'from-rose-500/15 via-transparent to-blue-500/10',
        groups: [
            {
                id: 'orders',
                title: 'Sales Order Defaults',
                description: 'Controls sales order generation and standard payment terms.',
                settings: [
                    {
                        key: 'sales.order.numberPrefix',
                        label: 'Sales order number prefix',
                        helpText: 'Prefix applied to generated sales order numbers.',
                        type: 'STRING',
                        category: 'sales',
                        control: 'input',
                        defaultValue: 'SO',
                        placeholder: 'SO',
                    },
                    {
                        key: 'sales.order.defaultPaymentTermDays',
                        label: 'Default customer payment term (days)',
                        helpText: 'Default payment term used on customer-facing sales orders.',
                        type: 'NUMBER',
                        category: 'sales',
                        control: 'input',
                        defaultValue: 15,
                        min: 0,
                        step: 5,
                    },
                ],
            },
            {
                id: 'fulfillment',
                title: 'Fulfillment Rules',
                description: 'Controls how fulfillment proceeds after sales orders are confirmed.',
                settings: [
                    {
                        key: 'sales.fulfillment.requireReservationBeforePick',
                        label: 'Require reservation before picking',
                        helpText: 'Ensure stock is reserved before downstream fulfillment begins.',
                        type: 'BOOLEAN',
                        category: 'sales',
                        control: 'boolean',
                        defaultValue: true,
                    },
                    {
                        key: 'sales.fulfillment.autoCreatePickList',
                        label: 'Auto-create pick lists',
                        helpText: 'Generate pick lists automatically when sales orders become actionable.',
                        type: 'BOOLEAN',
                        category: 'sales',
                        control: 'boolean',
                        defaultValue: false,
                    },
                ],
            },
        ],
    },
    {
        id: 'pos',
        title: 'POS and Counter Operations',
        description: 'Controls terminal behavior, receipts, offline flow, and cashier accountability.',
        icon: 'point_of_sale',
        accent: 'from-indigo-500/15 via-transparent to-emerald-500/10',
        groups: [
            {
                id: 'register',
                title: 'Register and Shift Policy',
                description: 'Rules for opening, closing, and supervising cashier shifts.',
                settings: [
                    {
                        key: 'pos.register.requireOpenShiftBeforeSale',
                        label: 'Require open shift before sale',
                        helpText: 'Prevent sales when no active cashier shift is open on the terminal.',
                        type: 'BOOLEAN',
                        category: 'pos',
                        control: 'boolean',
                        defaultValue: true,
                        risk: 'critical',
                    },
                    {
                        key: 'pos.register.allowManualCloseWithOfflineQueue',
                        label: 'Allow closing with offline queue',
                        helpText: 'Permit shift close even when unsynced offline sales remain on the device.',
                        type: 'BOOLEAN',
                        category: 'pos',
                        control: 'boolean',
                        defaultValue: false,
                        risk: 'standard',
                    },
                ],
            },
            {
                id: 'receiptAndOffline',
                title: 'Receipt and Offline Behavior',
                description: 'Receipt display rules and sync behavior when working offline.',
                settings: [
                    {
                        key: 'pos.receipt.footerText',
                        label: 'POS receipt footer',
                        helpText: 'Footer text printed on POS receipts.',
                        type: 'STRING',
                        category: 'pos',
                        control: 'textarea',
                        defaultValue: 'All sales are subject to the store return policy.',
                        placeholder: 'Receipt footer text',
                    },
                    {
                        key: 'pos.offline.autoSyncOnReconnect',
                        label: 'Auto-sync when connection returns',
                        helpText: 'Automatically upload queued offline sales once connectivity returns.',
                        type: 'BOOLEAN',
                        category: 'pos',
                        control: 'boolean',
                        defaultValue: true,
                    },
                    {
                        key: 'pos.cashier.allowManualDiscount',
                        label: 'Allow manual cashier discounts',
                        helpText: 'Permit price discounts without manager override at the terminal.',
                        type: 'BOOLEAN',
                        category: 'pos',
                        control: 'boolean',
                        defaultValue: false,
                        risk: 'standard',
                    },
                ],
            },
        ],
    },
    {
        id: 'analytics',
        title: 'Analytics and Reporting',
        description: 'Default reporting scope, export behavior, and dashboard operating rules.',
        icon: 'monitoring',
        accent: 'from-cyan-500/15 via-transparent to-violet-500/10',
        groups: [
            {
                id: 'dashboardDefaults',
                title: 'Dashboard Defaults',
                description: 'Controls how reporting dashboards load for users by default.',
                settings: [
                    {
                        key: 'analytics.dashboard.defaultDateRange',
                        label: 'Default dashboard date range',
                        helpText: 'Used as the starting time window on dashboards and analytics views.',
                        type: 'ENUM',
                        category: 'analytics',
                        control: 'select',
                        options: [
                            { value: '7', label: 'Last 7 days' },
                            { value: '30', label: 'Last 30 days' },
                            { value: '90', label: 'Last 90 days' },
                        ],
                        defaultValue: '30',
                    },
                    {
                        key: 'analytics.reports.defaultExportFormat',
                        label: 'Default export format',
                        helpText: 'Preferred export format for standard reports and generated data.',
                        type: 'ENUM',
                        category: 'analytics',
                        control: 'select',
                        options: [
                            { value: 'CSV', label: 'CSV' },
                            { value: 'XLSX', label: 'XLSX' },
                            { value: 'PDF', label: 'PDF' },
                        ],
                        defaultValue: 'CSV',
                    },
                ],
            },
        ],
    },
    {
        id: 'accounting',
        title: 'Accounting Foundation',
        description: 'Controls the inventory subledger, posting queue behavior, and export readiness for downstream accounting.',
        icon: 'account_balance',
        accent: 'from-emerald-500/15 via-transparent to-teal-500/10',
        groups: [
            {
                id: 'posting',
                title: 'Posting Policy',
                description: 'Defines how financially relevant inventory events are queued and exposed for export.',
                settings: [
                    {
                        key: 'accounting.posting.enabled',
                        label: 'Emit financial events',
                        helpText: 'Create posting-ready financial events and subledger entries for operational workflows.',
                        type: 'BOOLEAN',
                        category: 'accounting',
                        control: 'boolean',
                        defaultValue: true,
                        risk: 'critical',
                    },
                    {
                        key: 'accounting.posting.mode',
                        label: 'Posting mode',
                        helpText: 'Keep Phase 1 in a posting-ready state without a full general ledger module.',
                        type: 'ENUM',
                        category: 'accounting',
                        control: 'select',
                        options: [
                            { value: 'PENDING_ONLY', label: 'Pending only' },
                            { value: 'EXPORT_READY', label: 'Export ready' },
                        ],
                        defaultValue: 'PENDING_ONLY',
                    },
                ],
            },
            {
                id: 'costing',
                title: 'Cost and Valuation Hooks',
                description: 'Defaults for cost-of-goods and landed-cost integration boundaries.',
                settings: [
                    {
                        key: 'accounting.costing.enableCogsHooks',
                        label: 'Enable COGS hooks',
                        helpText: 'Emit subledger lines for inventory relief and cost-of-goods recognition.',
                        type: 'BOOLEAN',
                        category: 'accounting',
                        control: 'boolean',
                        defaultValue: true,
                    },
                    {
                        key: 'accounting.landedCost.allocationMethod',
                        label: 'Landed cost allocation',
                        helpText: 'Default policy used when landed-cost allocation is expanded in a later phase.',
                        type: 'ENUM',
                        category: 'accounting',
                        control: 'select',
                        options: [
                            { value: 'BY_VALUE', label: 'By value' },
                            { value: 'BY_QUANTITY', label: 'By quantity' },
                        ],
                        defaultValue: 'BY_VALUE',
                    },
                ],
            },
        ],
    },
    {
        id: 'integrations',
        title: 'Integrations and System',
        description: 'Webhooks, device defaults, and maintenance-related controls.',
        icon: 'hub',
        accent: 'from-slate-500/15 via-transparent to-blue-500/10',
        groups: [
            {
                id: 'webhooks',
                title: 'Webhooks and Delivery',
                description: 'Controls retry behavior and delivery defaults for outbound events.',
                settings: [
                    {
                        key: 'integration.webhooks.enabled',
                        label: 'Enable outbound webhooks',
                        helpText: 'Allow business events to be delivered to configured webhook endpoints.',
                        type: 'BOOLEAN',
                        category: 'integration',
                        control: 'boolean',
                        defaultValue: true,
                    },
                    {
                        key: 'integration.webhooks.retryLimit',
                        label: 'Webhook retry limit',
                        helpText: 'Maximum number of retry attempts after a failed webhook delivery.',
                        type: 'NUMBER',
                        category: 'integration',
                        control: 'input',
                        defaultValue: 3,
                        min: 0,
                        step: 1,
                    },
                ],
            },
            {
                id: 'devices',
                title: 'Devices and Maintenance',
                description: 'Defaults for printing and data retention.',
                settings: [
                    {
                        key: 'integration.devices.defaultReceiptPrinter',
                        label: 'Default receipt printer',
                        helpText: 'Friendly name or identifier of the primary receipt printer.',
                        type: 'STRING',
                        category: 'integration',
                        control: 'input',
                        defaultValue: 'Front Desk Printer',
                        placeholder: 'Printer name',
                    },
                    {
                        key: 'integration.system.auditRetentionDays',
                        label: 'Audit retention (days)',
                        helpText: 'Default retention period for settings and business audit logs.',
                        type: 'NUMBER',
                        category: 'integration',
                        control: 'input',
                        defaultValue: 365,
                        min: 30,
                        step: 30,
                    },
                ],
            },
        ],
    },
];

export const SETTINGS_INDEX = SETTINGS_SECTIONS.flatMap((section) => section.groups.flatMap((group) => group.settings.map((setting) => ({
    ...setting,
    sectionId: section.id,
    sectionTitle: section.title,
    groupId: group.id,
    groupTitle: group.title,
    groupDescription: group.description,
}))));

export const SETTINGS_MAP = Object.fromEntries(SETTINGS_INDEX.map((setting) => [setting.key, setting]));
